{% set name = "cmapy" %}
{% set version = "0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 741d27a56e4c836bbad3fffe3c99fdf3c206313301efcb43b52de9e87ae256f1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - matplotlib
    - numpy
    - OpenCV >=3.3.0
    - python >=3

test:
  imports:
    - cmapy

about:
  home: https://gitlab.com/cvejarano-oss/cmapy/
  license: MIT
  license_file: LICENSE
  summary: Use Matplotlib colormaps with OpenCV in Python.

extra:
  recipe-maintainers:
    - apcamargo
