travis:
  secure:
    BINSTAR_TOKEN: lQhfPMKlcjoj0rZVLgtSLqp1UewSPIAh5YbpkT5DJi3YUR66KrINwmCoKILCqL8vBcJRzs43xK2Vylq+CVJ27alDnIgXXF34sarcKz3psCijR8o6XIi6y544P10dT+wDE3uiBq1f72q/fvRbkLKWkVh11y6sy8HTH9S2xGUKMc2FIUcgAZkDvLiolN3LQsMgeYr9vqnW9buWz2E66QLqWkRgRrvn6b4rs1azLpUg/MyIiy42Fi2r0DJd4zuTdZFrtMYSDJxJeUGD+j01n1APl8MXrWRObD19tfO82/Qme/Lqr1pbH2d6/PuM4Kc8iCQ9TW7NwnIzObmwJRzi9Y1vzOxszwV469v8oG7YmJmSzaA2Ssr4ZiIRqjHcT09R2uE52WOfYWoisjHvx6r/d+hR8v2k33Yk7Jz8EK9ledhMpb0gCzJzkoPQaR1UVh6o1Smxl7RvxurilBBJIrjkBRN+Vob/rn9kwQ9LK345Hf1BIg1tOnsCkV1x86L5A2aLuQeIA8Sfa3KmvivTW+tTSFjUWS2CI4tndCLa25JYhvqJbBnHR/CUA6VKO6dET+OFie5qmIN0rBPkZXPP3KsRbveYyqtmBR+G2+ZDnXYvl3Ylf4oaP+xSSsMhZFzEGtGbh82vcorByv1prw3SFLNNXHFnRG9tNNoU+2CnlSixxUEQ0hw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
